project_id = "xhkdwfpnmjvmfbmokvct"

[functions.generate-report-preview]
verify_jwt = false

[functions.generate-monthly-preview]
verify_jwt = false

[functions.notify-production-status]
verify_jwt = false

[functions.send-production-report]
verify_jwt = false
