project_id = "eknqsstybtmmofphyvmj"

[functions.generate-report-preview]
verify_jwt = false

[functions.generate-monthly-preview]
verify_jwt = false

[functions.notify-production-status]
verify_jwt = false

[functions.send-production-report]
verify_jwt = false

[functions.send-scheduled-production-report]
verify_jwt = false

[functions.check-finalized-orders]
verify_jwt = false

[functions.send-scheduled-estoque-report]
verify_jwt = false

[functions.send-scheduled-compras-report]
verify_jwt = false

[functions.send-estoque-report]
verify_jwt = false
