
-- Convert all NO ACTION FKs referencing user_profiles or auth.users to ON DELETE SET NULL
ALTER TABLE public.user_profiles DROP CONSTRAINT IF EXISTS user_profiles_invited_by_fkey, ADD CONSTRAINT user_profiles_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.user_permissions DROP CONSTRAINT IF EXISTS user_permissions_created_by_fkey, ADD CONSTRAINT user_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.user_invitations DROP CONSTRAINT IF EXISTS user_invitations_invited_by_fkey, ADD CONSTRAINT user_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.clientes DROP CONSTRAINT IF EXISTS clientes_vendedor_id_fkey, ADD CONSTRAINT clientes_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.leads DROP CONSTRAINT IF EXISTS leads_especialista_id_fkey, ADD CONSTRAINT leads_especialista_id_fkey FOREIGN KEY (especialista_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.leads DROP CONSTRAINT IF EXISTS leads_vendedor_id_fkey, ADD CONSTRAINT leads_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.lead_history DROP CONSTRAINT IF EXISTS lead_history_user_id_fkey, ADD CONSTRAINT lead_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.follow_ups DROP CONSTRAINT IF EXISTS follow_ups_user_id_fkey, ADD CONSTRAINT follow_ups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.orcamentos DROP CONSTRAINT IF EXISTS orcamentos_vendedor_id_fkey, ADD CONSTRAINT orcamentos_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_vendedor_id_fkey, ADD CONSTRAINT pedidos_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.metas_vendas DROP CONSTRAINT IF EXISTS metas_vendas_vendedor_id_fkey, ADD CONSTRAINT metas_vendas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.knowledge_articles DROP CONSTRAINT IF EXISTS knowledge_articles_author_id_fkey, ADD CONSTRAINT knowledge_articles_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.report_configs DROP CONSTRAINT IF EXISTS report_configs_created_by_fkey, ADD CONSTRAINT report_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.excluded_orders DROP CONSTRAINT IF EXISTS excluded_orders_created_by_fkey, ADD CONSTRAINT excluded_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.production_orders DROP CONSTRAINT IF EXISTS production_orders_updated_by_fkey, ADD CONSTRAINT production_orders_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.hidden_production_orders DROP CONSTRAINT IF EXISTS hidden_production_orders_hidden_by_fkey, ADD CONSTRAINT hidden_production_orders_hidden_by_fkey FOREIGN KEY (hidden_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.default_role_permissions DROP CONSTRAINT IF EXISTS default_role_permissions_created_by_fkey, ADD CONSTRAINT default_role_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.politica_comercial_itens DROP CONSTRAINT IF EXISTS politica_comercial_itens_created_by_fkey, ADD CONSTRAINT politica_comercial_itens_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.perfil_precos DROP CONSTRAINT IF EXISTS perfil_precos_created_by_fkey, ADD CONSTRAINT perfil_precos_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.transportadoras DROP CONSTRAINT IF EXISTS transportadoras_created_by_fkey, ADD CONSTRAINT transportadoras_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.estoque_itens DROP CONSTRAINT IF EXISTS estoque_itens_created_by_fkey, ADD CONSTRAINT estoque_itens_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.estoque_movimentacoes DROP CONSTRAINT IF EXISTS estoque_movimentacoes_usuario_id_fkey, ADD CONSTRAINT estoque_movimentacoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.production_report_schedule DROP CONSTRAINT IF EXISTS production_report_schedule_created_by_fkey, ADD CONSTRAINT production_report_schedule_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.lead_prospecting_configs DROP CONSTRAINT IF EXISTS lead_prospecting_configs_created_by_fkey, ADD CONSTRAINT lead_prospecting_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.lead_prospecting_results DROP CONSTRAINT IF EXISTS lead_prospecting_results_reviewed_by_fkey, ADD CONSTRAINT lead_prospecting_results_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.ticket_attachments DROP CONSTRAINT IF EXISTS ticket_attachments_uploaded_by_fkey, ADD CONSTRAINT ticket_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
