// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqltnuyfwobzkdmxqrqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbHRudXlmd29iemtkbXhxcnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDY3MjEsImV4cCI6MjA2OTI4MjcyMX0.GKhHagERNyn8iyIBVtGJFYF1w3CglvuYRKmKfBDFZwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});